-- Algumas funções podem funcionar com qualquer tipo. Nesses casos, não defina o
-- cabeçalho dessas funções.
-- Use definições locais caso seja necessário criar funções auxiliares e calcular valores
-- repetidos ou que envolvam mais de uma operação.
-- 1. Crie uma função que inverte uma lista usando recursão em cauda.
-- 2. Crie uma função que recebe uma lista de notas (Float) de alunos, calcula a média e retorna
-- uma String como resultado, sendo que: se a média < 4.0, o resultado é “REPROVADO”; se a
-- 4.0 <= média < 6.0, o resultado é “RECUPERACAO”; e se média >= 6.0, o resultado é
-- “APROVADO”.
-- 3. Crie uma função que recebe um inteiro n e retorna uma lista com os n primeiros elementos da
-- série de Fibonacci.
-- 4. Crie a função equacao2grau a b c que retorna as raízes reais da equação do segundo grau
-- (ax² + bx + c = 0) em uma lista (a não pode ser zero). Use definição local para calcular o delta.
-- 5. Crie uma função que recebe um inteiro n e uma lista e retorna uma lista de listas que
-- corresponde à lista original dividida em n partes.